sudo: false

language: php

dist: trusty

php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer install

script:
  - >
    echo "Running unit tests";
    .build/vendor/bin/phpunit --coverage-text

  - >
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" -exec php -l {} >/dev/null \;
