sudo: false

language: php

dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION="dev-master"
    - php: 7.0
      env: TYPO3_VERSION="dev-master"
  allow_failures:
    - env: TYPO3_VERSION="dev-master"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer install
  - composer require typo3/cms="$TYPO3_VERSION"

script:
  - >
    echo "Running unit tests";
    .build/vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml

  - >
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" -exec php -l {} >/dev/null \;

after_success:
  - travis_retry .build/vendor/bin/coveralls -v
