sudo: false

language: php

dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - TYPO3_VERSION=^8.7
        - ANALYSIS='true'
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION="dev-master"
    - php: 7.0
      env: TYPO3_VERSION="dev-master"
  allow_failures:
    - env: TYPO3_VERSION="dev-master"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ "$ANALYSIS" != 'true' ]]; then if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi; fi
  - composer self-update
  - composer --version

before_script:
  - composer install
  - composer require typo3/cms="$TYPO3_VERSION"

script:
  - find . -name \*.php ! -path "./.build/*" -exec php -l {} >/dev/null \;
  - if [[ "$ANALYSIS" != 'true' ]]; then .build/vendor/bin/phpunit ; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then .build/vendor/bin/phpunit --coverage-text --coverage-clover clover.xml ; fi

after_success:
  - if [[ "$ANALYSIS" == 'true' ]]; then travis_retry .build/vendor/bin/coveralls -v ; fi
